# Generated by Django 5.1 on 2024-08-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="adv.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="advert",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="adv.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="advert",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="advert",
            name="description",
            field=models.TextField(verbose_name="Описание объявления"),
        ),
        migrations.AlterField(
            model_name="advert",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок объявления"),
        ),
        migrations.AlterField(
            model_name="advert",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Название города"),
        ),
    ]
